### ISSUE TITLE
Cocealment

### ISSUE THREAD

**Issue by rexxar-tc** [rexxar-tc/EssentialsPlugin#11]
It's kind of broken? Maybe? I don't even know.

**Comment by AnonymousMonkey75** [comment]
I'm not sure if I follow what you mean in your update. Concealment always revealed grids when players were close to them. You said that is what is occurring now? So they won't reveal on login so you can't spawn at med bays? Is that correct?

**Comment by rexxar-tc** [comment]
No, everything should load in correctly when you first join the game. What's _supposed_ to happen is the grid will immediately load for the client if it's in draw distance, but Keen changed the way that function works quite some time ago. I'm looking for a replacement, but I'm putting the whole project on hold for a few weeks because of school.

**Comment by AnonymousMonkey75** [comment]
K, so how close does someone have to be?

**Comment by rexxar-tc** [comment]
About 900m. It seems to vary, and I have no idea why.

**Comment by AnonymousMonkey75** [comment]
Hrm

**Comment by rexxar-tc** [comment]
Lemme try to explain this better; the conceal distance setting should still work correctly. The server will conceal and reveal grids based on the conceal distance. The problem is that the client won't re-load concealed grids until they get within 1km. There's some sort of sync problem and it's causing problems with most of the Essentials systems. I'm working on a fix, but I'm very short of time because of school.

**Comment by AnonymousMonkey75** [comment]
Got ya, for what its worth I tried out concealment just now. Had no spawn points. So turned it off.

**Comment by AnonymousMonkey75** [comment]
Actually, it removed all those grids from my save. My sbs went from 140MB to 12MB just by turning on concealment. Something not right.

**Comment by rexxar-tc** [comment]
Jesus christ, how is your sbs 140MB?!

It should only delete entities if it finds duplicates. Check your log file, it should have a whole bunch of DUPE FOUND messages.

**Comment by AnonymousMonkey75** [comment]
It's 140MB because I have 312 active players. 312 in the past 15 days have an active turret. That's the metric I use. Players whom do not login for 15 days are removed as is theirs grids. 

There are about 700 grids in my world. There are no duplicates.

**Comment by AnonymousMonkey75** [comment]
I'll fork your version and see what i can do with it. I ran my own SESE and Essentials, forked from Tyrsis latest release for many moons after Tyrsis quit. Was burning out so I stopped updating it after 104. Never really shared it, it was on my github but I had 0 interest in supporting it. I have since deleted the repos.  I commend you for doing so, it's a job I do not want.

**Comment by rexxar-tc** [comment]
When I say duplicates, I mean that sometimes Essentials doesn't conceal or reveal a grid correctly, and it ends up with two copies in memory. When it finds two entities with the same ID, it deletes one of them. This is the only time it deletes an entity completely.

When Essentials conceals a grid, it deletes the entity, but immediately re-creates it out of scene. I can only think of two situations that would cause it to just delete everything, and that's if it thinks every grid is duplicated somehow, or if it can't create grids correctly. I really don't know what would cause that, though.

**Comment by AnonymousMonkey75** [comment]
Right, I'm with ya. 

Seems to be working OK now but still not working with med bays. Not revealing the grids before the med bay list shows up.

**Comment by rexxar-tc** [comment]
Every time I try concealment, it reveals every grid twice, which causes spectacular explosions. Are you getting that? It looks to me like the game is generating a new entity ID for any grid that gets created. Not sure if that changed on Keen's end, or if it's my new method of creating entities.

Medbay is another issue, and I'm betting it's an outdated API call into SE.

**Comment by rexxar-tc** [comment]
As it turns out, _I_ broke concealment. Oops.

It works as it should now; I added some replication calls to force the client to sync concealed/revealed grids.

For some reason, when the entity is recreated out of scene, it leaves all armor blocks in place, but they have no physics. I'm pretty sure this is a problem with SE, but I kinda like it. You can still see ships that are concealed, but the server isn't processing them.

On to another problem until I can get some feedback on this.
