### ISSUE TITLE
Not working: /admin move player to/position, Can not find user or grid with the name...

### ISSUE THREAD

**Issue by tbankstemp** [rexxar-tc/EssentialsPlugin#22]
No need to reply, just adding a bug report.

If I run "/admin move player position (playername) it gives this: 
Doesn't look like there's any errors thrown, the server just says "Can not find user or grid with the name: (playername)"

If I run "/admin move player to (playername targetplayername) it doesn't give any errors or notifications as to what it did, it just doesn't do anything.

Thanks Rexxar!!!

**Comment by rexxar-tc** [comment]
Are you sure those are the right commands? That error message only appears in /move player to

**Comment by tbankstemp** [comment]
Yes, you're right I switched them up, sorry bout that. 
The "move player to" error is: "Server - Can not find user or grid with the name: (playername)"
The "move player position" doesn't show anything.

**Comment by rexxar-tc** [comment]
Fixed. New release in a few days, probably.
