### ISSUE TITLE
/settings setmotd doesn't work

### ISSUE THREAD

**Issue by 88tom** [rexxar-tc/EssentialsPlugin#23]
this is the message that appear:
2015-12-07 21:59:29.2981|Info|EssentialsPlugin.Essentials.HandleChatMessage|ChatHandler Error: System.IndexOutOfRangeException: Indice oltre i limiti della matrice.
   in EssentialsPlugin.ChatHandlers.Settings.HandleSettingsSetMOTD.HandleCommand(UInt64 userId, String[] words)
   in EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)

**Comment by rexxar-tc** [comment]
How did you type the command? It can get picky sometimes.

**Comment by rexxar-tc** [comment]
Looks like I forgot to check the length of an array before I read values from it. It'll work if you supply all five arguments. The fix is easy, but I don't have any time to do it; it's finals week, and real life has taken over.

**Comment by 88tom** [comment]
No problem rexxar, i will try today with all arguments..

**Comment by 88tom** [comment]
Ok it work.

**Comment by rexxar-tc** [comment]
Good. I'll patch it in the next build; sometime in the next few weeks.
