### ISSUE TITLE
Feature Request: GetOutMySandbox(world file cleaner)

### ISSUE THREAD

**Issue by SilentSymphony** [rexxar-tc/EssentialsPlugin#27]
while dodexahedron was managing the extender he created a plugin called GetOutOfMySandbox which is available here https://github.com/SEServerExtender/GetOutOfMySandboxPlugin however this plugin does not seem to function for me with the current version of extender, This plugin did wonders to reduce the file size of the maps by removing player data for players who did not own ships

This plugin while great lacked one function that i felt it required to be complete, removal of factions that have 0 members usually caused by the plugin deleting the player data and thus emptying out the faction.

Factions being cleaned out along with the old player data i feel is a quality of life improvement on top of the other benefits to the server players would more easily be able to navigate through active factions instead of 50-100 dead factions.

I would really love to see something similar to this make a return to extender in some way be it an updated or new plugin if not an integrated feature of essentials itself.

**Comment by rexxar-tc** [comment]
This is already on the roadmap. I'll probably end up just repairing the plugin rather than copy features into Essentials. I feel like Essentials is starting to get bloated.
