### ISSUE TITLE
[v1.13.4.334-alpha] Grid Duplication Issues

### ISSUE THREAD

**Issue by EngineerBean** [rexxar-tc/EssentialsPlugin#28]
I've been experiencing some very bad duplication of multiple grids in my server with this version. Small and Large Grids are both being affected. Had to disable concealment for now until this issue is resolved.

**Comment by rexxar-tc** [comment]
I changed something in the last SESE update that affected entity management, have you updated?

**Comment by SilentSymphony** [comment]
My users have not reported any grid duplication but there have been some mysteriously damaged grids so I'm not completely sure I'm not having the same issue.. but i have not seen concrete proof of duplication yet on the latest version.

edit: will report back if i can catch this happening.

**Comment by EngineerBean** [comment]
I definitely did update. With my concealment settings I have set 10000m activate, large grid conceal and no medbay conceal. I did notice with all the grids that were duped, your commrelay was affected too. All grids that were duped were ones that had been concealed.

**Comment by rexxar-tc** [comment]
Did this happen before or after the SESE update? It's _possible_ that the change I made in SESE could duplicate grids, even though it really shouldn't.

SilentSymphony, I've heard similar things from others. This used to be a problem in SE a long time ago, maybe it's come back with Keen tinkering in the netcode?

**Comment by EngineerBean** [comment]
Yes, this did seem to happen after the latest update to SESE

**Comment by rexxar-tc** [comment]
I'll look into it, for now just roll back your SESE version.

**Comment by EngineerBean** [comment]
Have not had a repeat of this issue since first occured, probably one off. Closing issue...
