### ISSUE TITLE
[feature] faction manager

### ISSUE THREAD

**Issue by 88tom** [rexxar-tc/EssentialsPlugin#29]
hi rexxar, is possible to manage the factions of the server? add player to faction, modify permission etc? actually i saw only delete faction :)

**Comment by rexxar-tc** [comment]
It's possible, yes, but I don't think it will be in Essentials. Maybe a separate faction/player management plugin.

**Comment by togosh** [comment]
@88tom Check out Midspace's Admin Commands Mod
Steam Workshop: http://steamcommunity.com/sharedfiles/filedetails/?id=316190120
Faction Management Admin Commands: https://github.com/midspace/Space-Engineers-Admin-script-mod/wiki/Faction-management-Admin-Commands

**Comment by rexxar-tc** [comment]
Unfortunately, you can only use one mod at a time. Midspace's mod completely intercepts chat messages, so the server (and Essentials) don't see any commands. Once I figure out how to do the same, commands will only get sent to one of the mods. Probably the last one to get loaded in. I don't know if there's anything to be done about that, I'd have to work with Midspace on it.
