### ISSUE TITLE
/admin reveal force crashes server

### ISSUE THREAD

**Issue by EngineerBean** [rexxar-tc/EssentialsPlugin#32]
I have a few grids in the current world that are still being concealed, even though concealment has been disabled. When I use "Reveal Force" it crashes server. Is there a way to reveal these entities outside of SESE console ie..deleting or editing a file. This way I can resolve the problematic entities prior to loading the world.

**Comment by rexxar-tc** [comment]
Yup, open your SANDBOX_0_0_0_.sbs and search for <PersistentFlags>CastShadows</PersistentFlags> and replace it with <PersistentFlags>CastShadows InScene</PersistentFlags>

**Comment by EngineerBean** [comment]
Awesome, cheers for that.
