### ISSUE TITLE
[v1.13.5.32-alpha] Crash on startup

### ISSUE THREAD

**Issue by EngineerBean** [rexxar-tc/EssentialsPlugin#34]
After latest update from Keen I can't seem to be able to use Essentials plugin. Server shuts down shortly after its execution. Only log I seem to have is [SpaceEng-1-PluginLog-2016-01-15.log](http://pastebin.com/L3fY3Bnz)

**Comment by rexxar-tc** [comment]
Your Essentials is out of date. There's a new one posted in releases, but for some reason Github thinks I posted it two days ago, so it's second in the list.
